runtime: python39
entrypoint: gunicorn -b :$PORT main_app:app

instance_class: F4_1G

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: config/firebase/serviceAccount.json

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
- url: /api/user/login
  script: auto

- url: /api/scan-apple
  script: auto

- url: /api/history
  script: auto
  
- url: /.*
  script: auto