runtime: python39
entrypoint: gunicorn -b :$PORT main_app:app

instance_class: B4

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: config/firebase/serviceAccount.json

basic_scaling:
  max_instances: 10
  idle_timeout: 8m

handlers:
  - url: /api/user/login
    script: auto

  - url: /api/scan-apple
    script: auto

  - url: /api/history
    script: auto

  - url: /.*
    script: auto
